### PR TITLE
[iOS] Fix release notes localization

### PR DESCRIPTION
**Pull request by kandevis**
- Fix iOS release notes always return English.
- Added locale (iOS only) property to stick with &lang=locale (ex: &lang=vi_vn) Itunes search query

### CODE REVIEW

**Review by rodriguesJeff — APPROVED** [review]

**Comment by rodriguesJeff** [comment]
Brother! 
Thanks for contributing 
Something went wrong in flutter test on ci
Can you review it?

**Comment by kandevis** [comment]
I copy my code from local pub project and forgot to edit the test case. Sorry. Updating now

**Comment by kandevis** [comment]
Please check it again.

**Comment by rodriguesJeff** [comment]
Thanks for contributing!!!
I'll release a New version on pub.dev

**Pull request merged**
